# Load oh-my-zsh
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="wjakob"
plugins=(git zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
source ~/term-tools/config/shrc.sh

autoload up-line-or-beginning-search
autoload down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# OSX / iTerm2 key bindings
bindkey $terminfo[kbs]   backward-delete-char           # Backspace
bindkey $terminfo[kdch1] delete-char                    # Delete
bindkey $terminfo[khome] beginning-of-line              # Home
bindkey $terminfo[kend]  end-of-line                    # End
bindkey $terminfo[kpp]   up-line-or-history             # PageUp
bindkey $terminfo[knp]   down-line-or-history           # PageDown
bindkey $terminfo[kcuu1] up-line-or-beginning-search    # Down
bindkey $terminfo[kcud1] down-line-or-beginning-search  # Up
bindkey $terminfo[kcub1] backward-char                  # Left
bindkey $terminfo[kcuf1] forward-char                   # Right

# Search paths
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/projects/pbrt-3ed/src/bin

alias n=ninja

alias cmake_deb='cmake $@ -DCMAKE_BUILD_TYPE=DEBUG'
alias cmake_rel='cmake $@ -DCMAKE_BUILD_TYPE=RELEASE'
alias cmake_gcc='cmake $@ -DCMAKE_CXX_COMPILER=g++-5'
alias cmake_clang='cmake $@ -DCMAKE_CXX_COMPILER=clang++'
